name: minitorch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pylint             # let conda choose compatible version
  - datasets=2.4.0
  - dill               # conda will solve the version to satisfy both
  - pip:
      - altair==4.2.2
      - colorama==0.4.3
      - embeddings==0.0.8
      - hypothesis==6.54.0
      - networkx==3.3
      - numba==0.60.0
      - numpy==2.0.0
      - plotly==4.14.3
      - pre-commit==2.20.0
      - pydot==1.4.1
      - pytest==8.3.2
      - pytest-env==1.1.4
      - pytest-runner==5.2
      - python-mnist==0.7
      - streamlit==1.12.0
      - streamlit-ace==0.1.1
      - torch==2.7.1
      - typing_extensions==4.14.0
      - watchdog==1.0.2
